### ISSUE TITLE
undefined reference to `lxc_config_item_is_supported'

### ISSUE THREAD

**Issue by cyberwillis** [lxc/go-lxc#107]
Hi guys...
I just found this issue trying to compile lxd from the sources.

```
/tmp/go-build698508144/gopkg.in/lxc/go-lxc.v2/_obj/lxc-binding.o: In function `go_lxc_config_item_is_supported':
../../../gopkg.in/lxc/go-lxc.v2/lxc-binding.c:451: undefined reference to `lxc_config_item_is_supported'
```

For the moment I solved by returning `true`

**Comment by stgraber** [comment]
What version of liblxc were you using?

**Comment by cyberwillis** [comment]
I am using the latest, also built from source

Appear that all methods needs a structure to been passed for each method and this one doesn't have it.
The go version of this file has it but the C version does not.

**Comment by stgraber** [comment]
```
./src/lxc/lxccontainer.h:bool lxc_config_item_is_supported(const char *key);
```

So this is an exported symbol in LXC 3.0.0.
What does `grep -r lxc_config_item_is_supported /usr/include/lxc/` get you on your system?

I've also confirmed that current go-lxc builds just fine here with liblxc 3.0.1.

**Comment by cyberwillis** [comment]
the command print this.

`/usr/include/lxc/lxccontainer.h:bool lxc_config_item_is_supported(const char *key);`

I am building it in a virtual machine (VirtualBox Ubuntu 16.04) do you believe that because its a guest on systemd this could in some way present this as a problem ?

Anyway ... I verified that in a Host (instead of Guest machine) the build don't catch this error...

**Comment by cyberwillis** [comment]
I just found the "behaviour" ...
I have built the liblxc using --prefix=/usr earlier ,,, without this prefix the lxd make don't print this message.

Sorry about about that.
