### ISSUE TITLE
Wire up Travis CI

### ISSUE THREAD

**Issue by dcramer** [lxc/go-lxc#11]
Something as simple as https://github.com/dropbox/changes-client/blob/master/.travis.yml might work.

I'll submit a PR unless someone beats me to it.

**Comment by fatih** [comment]
Travis doesn't support lxc creation.

**Comment by dcramer** [comment]
Doh, didn't consider that.

**Comment by caglar10ur** [comment]
Maybe, we can split tests into two (and maybe mock some stuff too) so that we can run at least some of the tests in travis. I'm re-opening this for future...

**Comment by stgraber** [comment]
Splitting the testsuite into things that can run on travis and things that can't is usually a good idea. Then we can use the LXC Jenkins to run actual container tests.

**Comment by dijkstracula** [comment]
FYI, a lot seems to have changed with Travis as of late - I am able to get a project that depends on `go-lxc` to run a suite of container-mutating tests inside Travis by riding on the coattails of ["services: -docker"](https://docs.travis-ci.com/user/docker/).  I also had to install `lxc-dev` in the before-install runlist, and then patching around the cgroups issue reported [here](https://github.com/lxc/lxc/issues/181#issuecomment-37303903).

It's not clear that our usecases overlap exactly, but for executing basic container management functions and have them Do The Right Thing, this was successful.

**Comment by caglar10ur** [comment]
@dijkstracula sounds like a lot changes, yes. It also sounds like you are familiar with those changes. Would you be interested to sending a PR to run go-lxc tests under travis?

**Comment by caglar10ur** [comment]
I think we can close this now that @brauner's work in (https://travis-ci.org/lxc/go-lxc)
