### ISSUE TITLE
tag semantic releases

### ISSUE THREAD

**Issue by onlyjob** [lxc/go-lxc#132]
Please consider tagging formal semantic releases.

Thanks.

**Comment by stgraber** [comment]
We don't have a plan to do so at this time.
liblxc itself is versioned but go-lxc is made to work with all stable versions of liblxc and so doesn't need to follow its versioning.

Major API breaks do lead to version bumps on go-lxc though, as can be seen by the current version being v2.

**Comment by onlyjob** [comment]
This is so projects depending on this library (e.g. _nomad-driver-lxc_) could refer to it by proper release version.
Not every commit is compatible and API breakage already happened here.

**Comment by stgraber** [comment]
Most of the Go pinning tools work with hashes, so you can always pin on what you've last tested.
