### ISSUE TITLE
We need something like WaitIPAddresses to make sure the container's network is up

### ISSUE THREAD

**Issue by caglar10ur** [lxc/go-lxc#14]
https://github.com/lxc/lxc/blob/master/src/python-lxc/lxc/__init__.py#L326 does something similar so we can mimic it.

**Comment by caglar10ur** [comment]
@dcramer was looking at changes-client to see what you are doing and realized that (because of https://github.com/dropbox/changes-client/blob/f541a16c5c93047513601090ebe5f495136006c7/adapter/lxc/container.go#L125) this could be useful for you. Let me know what you think :)

**Comment by dcramer** [comment]
Yeah this is definitely useful. Thanks!
