### ISSUE TITLE
HasAPIExtension does not work because liblxc version check is broken

### ISSUE THREAD

**Issue by eraserix** [lxc/go-lxc#162]
On Ubuntu 22.04, liblxc has version reports version 5.0.0~git2209-g5a7b9ce67-0ubuntu1. The "~git..." part breaks the version check in runtimeLiblxcVersionAtLeast(), it always returns false.

LXD has a [copy of the same function](https://github.com/lxc/lxd/blob/75160b6467dfa7d2ecea031c7eb38fd15e23ebf9/lxd/instance/instance_utils.go#L1255) with a fix for exactly this problem.

**Comment by tomponline** [comment]
We should update this function and then get lxd to use it to avoid duplication.
