### ISSUE TITLE
How to create new virtual machine?

### ISSUE THREAD

**Issue by Gictorbit** [lxc/go-lxc#165]
Since `lxc` supports virtual machines as well as containers, is it possible to create a new vm using vm images?

**Comment by stgraber** [comment]
This is the `go-lxc` repo which is the binding for the low-level liblxc library. That library only handles containers.
What you're referring to is LXD's virtual machine support which uses QEMU to run virtual machines.

To do so, you need a running LXD daemon, then to drive it from Go, you can use the Go client for LXD (https://pkg.go.dev/github.com/lxc/lxd/client)

**Comment by Gictorbit** [comment]
Oh I see, thank you for your quick reply
