### ISSUE TITLE
‘struct lxc_container’ has no member named ‘set_timeout’

### ISSUE THREAD

**Issue by MYan42** [lxc/go-lxc#169]
# Necessary information

 * Distribution: Ubuntu 22.04
 * LXD git version tag: lxd-5.20 (6b2c9592)
 * go-lxc git version: ccae595aa49e779f7ecc9250329967aa546acd31

# Issue description
I am tring to build the lxd form source code following this [Tutorial](https://discuss.linuxcontainers.org/t/how-to-create-lxd-binaries-from-the-source-code-and-side-load-them-in-an-existing-snap-installation/16551).

After `make dep` and export the necessary variables, `make` facing issue while compile go-lxc part.
  ```
  $ make
  ......
  github.com/lxc/go-lxc
  # github.com/lxc/go-lxc
  lxc-binding.c: In function ‘go_lxc_set_timeout’:
  lxc-binding.c:80:15: error: ‘struct lxc_container’ has no member named ‘set_timeout’
     80 |         if (!c->set_timeout(c, timeout))
        |               ^~
  make: *** [Makefile:35: build] Error 1
  ```

I have also tried only compile go-lxc from source, facing the exact same error.

**Comment by stgraber** [comment]
Not a go-lxc issue, it's an issue because of broken LXC header files in Ubuntu.

The current build instructions (not that old tutorial) for both LXD and Incus include a mention of this problem and how to resolve it.

**Comment by stgraber** [comment]
https://linuxcontainers.org/incus/docs/main/installing/#install-incus-from-source
