### ISSUE TITLE
Package name of the tests package 

### ISSUE THREAD

**Issue by fatih** [lxc/go-lxc#3]
The package name is currently not `lxc`. Instead it's called `lxc_test`. Usually package names are the same as the base package name. There might be some exceptions which are listed here: http://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-in-go-lang 

As I know we can obey the usual way and rename the package to `lxc`. This also would enable to access private variables/identifiers. What do you think? If there is no other reason, I'll would like to change this.

**Comment by caglar10ur** [comment]
I ended up with this to leverage testing module to test external side of the package but I've no objections changing it's name to lxc and adding internal test cases as well.

**Comment by fatih** [comment]
Ok, I'll do the changes than. Going to open a pull request.

**Comment by caglar10ur** [comment]
Hmm a quick observation, I just checked the Go sources and lots of modules (like time, os, sort etc.) uses packagename_test name instead of package.

**Comment by fatih** [comment]
Yes. I think os and time was amongst the first std packages in Go. It's mixed. Packages like `net` `encoding/xxx`, `crypto` are using base package names. Usually when there is a higher abstraction that makes sense. It's up to you, but I think eventually there will be a time you are going to need the internal private identifiers. I'm open to all options.

**Comment by caglar10ur** [comment]
I agree, go for it :)
