### ISSUE TITLE
Ability to set config options directly instead of loading from configfile

### ISSUE THREAD

**Issue by syed** [lxc/go-lxc#38]
Currently it is not possible to set config options like lxc.network.hwaddr programatically. Is there a reason why? Can this be added?

**Comment by caglar10ur** [comment]
Not sure I understand the problem. As long as I know, you can set hwaddr manually and if you don't then one will be auto generated for you. Do you have a test case for the problem?

**Comment by syed** [comment]
Sorry just looked up the code. SetConfigItem is what I was looking for. I could not find that in the examples directory. Can I add one example?

**Comment by caglar10ur** [comment]
Of course! Please feel free to send a pull request and refer this.
