### ISSUE TITLE
Implement bdev specs

### ISSUE THREAD

**Issue by jtopjian** [lxc/go-lxc#43]
I have a simple Terraform provider for LXC and someone [reported](https://github.com/jtopjian/terraform-provider-lxc/issues/4) that they were unable to pass in options such as fstype, fssize, etc. 

As seen in the comments, I discovered that the bdev stuff isn't implemented in the go bindings.

How difficult would this be to implement? I'd be happy to give it a shot if someone could point me to something similar to look at.

Thanks!

**Comment by caglar10ur** [comment]
Yes, bdev_specs are missing in Go bindings (https://github.com/lxc/go-lxc/blob/v2/container.go#L331). I'm not sure how soon I can attack that so please feel free to work on it!

**Comment by jhance** [comment]
Basically they just pass a `NULL` where you need to pass bdevspecs. This should be simple to implement, really, and it completely blocks using LVM with these bindings
