### ISSUE TITLE
Package lxc was not found in the pkg-config search path

### ISSUE THREAD

**Issue by domitian** [lxc/go-lxc#44]
Hi,
i am trying to install go-lxc in my ubuntu system with the following command.

``` shell
go get gopkg.in/lxc/go-lxc.v2
```

I am getting the following error, even though i installed lxc with 'sudo apt-get install lxc'

``` shell
# pkg-config --cflags lxc
Package lxc was not found in the pkg-config search path.
Perhaps you should add the directory containing `lxc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lxc' found
exit status 1
```

When i do dpkg -l lxc, it is showing up there, but there is no executable by name 'lxc', only lxc-\* are available. 
My machine is ubuntu 14.04

**Comment by jochumdev** [comment]
Think you need to install lxc-dev.
