### ISSUE TITLE
Passing arbitrary strings to stdin of RunCommand

### ISSUE THREAD

**Issue by isage** [lxc/go-lxc#46]
Hello, basically i'm trying to pass bash script into stdin of "bash --login" running in RunCommand
http://paste.fedoraproject.org/265537/41873246/ "working" example
But all i get is "bash: error reading input file: Is a directory"

**Comment by isage** [comment]
Oh, i get it. LXC expects real file descriptors, while go io.Pipe provides pseudo-fds.
It works for os.Stdin.Fd() only because numbers match, meh.

**Comment by isage** [comment]
Or not.
It fails even with Fd from os.Open
Basically, it fails with anything, except os.Stdin

**Comment by isage** [comment]
http://paste.fedoraproject.org/265620/89528144/ but works in C as expected. Am i missing something?

**Comment by isage** [comment]
http://paste.fedoraproject.org/265631/41890555 minimal non-working go example. Which starts to work if i remove stdout or stderr redirection.

**Comment by caglar10ur** [comment]
@isage paste.fedoraproject.org links are all expired. Could you please attach the non-working example here If you think that's a bug.
