### ISSUE TITLE
default user/password?

### ISSUE THREAD

**Issue by benoittoulme** [lxc/go-lxc#47]
Hello,

I ran your example create.go, which creates a container named rubik. 
When I start it, I am not able to login properly. I thought default login/password would be ubuntu/ubuntu but it is not the case. 

Am I missing something?
Thanks.

**Comment by caglar10ur** [comment]
You can use LXC-Users mailing lists to ask questions - https://lists.linuxcontainers.org/listinfo/lxc-users

**Comment by benoittoulme** [comment]
Thank you for the link.
