### ISSUE TITLE
go get failing ubuntu 15.10

### ISSUE THREAD

**Issue by RushilPatel** [lxc/go-lxc#54]
go get gopkg.in/lxc/go-lxc.v2 results in below error
# pkg-config --cflags lxc

pkg-config: exec: "pkg-config": executable file not found in $PATH

**Comment by ranjib** [comment]
```
apt-get install -y pkg-config lxc-dev
```

and try again

**Comment by RushilPatel** [comment]
that worked!
Thanks!!
