### ISSUE TITLE
Container ops fork child processes that inherit file descriptors

### ISSUE THREAD

**Issue by dijkstracula** [lxc/go-lxc#66]
Dear go-lxc contributors,

I've observed a issue with concurrently creating file descriptors and performing container operations that involve fork/exec under the hood.  I have created a repro case [here](https://github.com/dijkstracula/go-lxc-cloexec-race); for more details, please see below:
### Description

go-lxc has a classic CLOEXEC race where the underlying liblxc C library will,
when we wish to start a new container, fork() and exec() the /sbin/init process,
but does not ensure that those children do not inherit file descriptors that have
been concurrently opened in the parent process.  As a result, because the inode
reference count will be higher than we expect, application code cannot assume
that close()ing a fd will behave the way we expect it to - in particular, closing
the write half of a pipe may not also close the read half of the pipe, leading to
deadlock-like behaviour.

In contrast, when the Go runtime wants to spawn a child process (e.g. in os/exec),
it takes a [lock](https://golang.org/src/syscall/exec_unix.go) to ensure mutual
exclusion.

We observed the aforementioned pipe hang on an internal project and created a [test case](https://github.com/dijkstracula/go-lxc-cloexec-race) that exhibits the same behaviour.
### Example

```
➜ $ go run main.go
Attempting race with starting go runtime pid 20297
Started precise (init pid: 20342; parent pid: 20306)
Found the following intersecting inodes: [505657 505657]
*** inode race detected after 1 attempts
```

We can confirm this with manual `lsof`ing:

```
➜  $ sudo lsof -p 20306 | grep 505657
main    20306 vagrant    4r  FIFO               0,10      0t0     505657 pipe
main    20306 vagrant    5w  FIFO               0,10      0t0     505657 pipe
➜  $ sudo lsof -p 20297 | grep 505657
main    20297 vagrant    4r  FIFO   0,10      0t0  505657 pipe
main    20297 vagrant    5w  FIFO   0,10      0t0  505657 pipe
```

The relevant bits of the process tree:

```
vagrant   1776  0.0  0.2  50392 11752 pts/0    Ss   14:38   0:01  |       \_ /bin/zsh -l
vagrant  20274  1.2  0.2 127188 11352 pts/0    Sl+  23:45   0:00  |           \_ go run main.go
vagrant  20297  0.0  0.1 136304  4844 pts/0    Sl+  23:45   0:00  |               \_ /tmp/go-build525531552/command-line-arguments/_obj/exe/main
...
vagrant  20306  0.0  0.0 144732  3932 ?        Ss   23:45   0:00 /tmp/go-build525531552/command-line-arguments/_obj/exe/main
100000   20342  1.0  0.0  24072  3148 ?        Ss   23:45   0:00  \_ /sbin/init
100000   20523  0.0  0.0  15196   184 ?        S    23:45   0:00      \_ upstart-socket-bridge --daemon
100000   20541  0.0  0.0  17240   168 ?        S    23:45   0:00      \_ upstart-udev-bridge --daemon
```
### Suggested fixes

Because the fork() happens in C-land, I'm not sure of a completely clean solution.
One thing that comes to mind that might work is a double-fork, where we let the go
runtime fork first, to ensure that no concurrent fd creation could have been inherited,
and then we let liblxc do its thing.  I don't know if such a low-level primitive is
exposed up into golang "userspace", though.

Thank you,
Nathan

**Comment by caglar10ur** [comment]
Hey @dijkstracula, 

Thank you so much for the super detailed report and also for the sample code to reproduce it! 

I'll try to take a look at it but unfortunately I'm crazy busy nowadays :/ 

Not sure whether double fork would be a solution, need to try it :) @tych0 do you have any suggestions?

**Comment by tych0** [comment]
You can set the container's `daemonize` flag via `container.WantDaemonize(true)`, which should invoke liblxc's code to close these fds. It also implies a few other things about forking that you might or might not want, I don't remember exactly the specifics.

We could also replicate `lxc_check_inherited` in golang, but it might make more sense to somehow expose it in a nicer way to liblxc. But maybe just setting daemonize will be enough, so I'd suggest you try that first :)

**Comment by dijkstracula** [comment]
Thank you, @tych0!  It appears that in the repro case setting `WantDaemonize(true)` seems to avoid the race.  Today I'll backport the "fix" in the service at work (which was, unfortunately, just to shell out to the LXC CLI :( ) and see if that also solves our issue.

Do you reckon that this ought to be the default setting for go-lxc containers?  Is there a reason why application developers would not want this flag enabled by default?

**Comment by tych0** [comment]
On Mon, Sep 26, 2016 at 08:46:16AM -0700, Nathan Taylor wrote:

> Thank you, @tych0!  It appears that in the repro case setting `WantDaemonize(true)` seems to avoid the race.  Today I'll backport the "fix" in the service at work (which was, unfortunately, just to shell out to the LXC CLI :( ) and see if that also solves our issue.
> 
> Do you reckon that this ought to be the default setting for go-lxc containers?  Is there a reason why application developers would not want this flag enabled by default?

Possibly, although someone should look at what the repercussions are
for setting it by default. It implies a bunch of things, and I don't
remember exactly what they are :).

Probably it shouldn't be go-lxc making this decision to change the
default, but liblxc itself, since it is the one providing the C api.

**Comment by caglar10ur** [comment]
@tych0 @dijkstracula ah sorry for not mentioning that, for some reason I assumed you already tried WantDaemonize. You should also be able set WantCloseAllFds to instruct liblxc to do the same.

**Comment by dijkstracula** [comment]
Apologies for the delay!

Yes, it turns out WantDaemonize was the thing I wanted; unclear how I kept missing it.
