### ISSUE TITLE
go get returns 301

### ISSUE THREAD

**Issue by mettke** [lxc/go-lxc#74]
Running 
```bash
go get gopkg.in/lxc/go-lxc.v2
```
returns a 'Moved Permanently' HTTP Code:
```plain
# cd .; git clone https://gopkg.in/lxc/go-lxc.v2 /data/Projects/gitlab/gitlab-ci-multi-runner/src/gopkg.in/lxc/go-lxc.v2
Cloning into '/tmp/src/gopkg.in/lxc/go-lxc.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/lxc/go-lxc.v2: exit status 128
```

**Comment by stgraber** [comment]
It's a known issue with gopkg.in and some versions of git.

The workaround they currently give is:

    git config --global http.https://gopkg.in.followRedirects true


There's nothing we can do at the go-lxc level, it's something gopkg.in needs to figure out.
