### ISSUE TITLE
go get fails for 8e4bc27  

### ISSUE THREAD

**Issue by towe75** [lxc/go-lxc#79]
Hi,

this morning one of our builds failed. It turned out that a go get go-lxc.v2 does not work anymore.
I can reproduce the problem:

    export GOPATH=/tmp
    root@buildroot-trusty:/# apt-get install -y pkg-config lxc-dev
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    lxc-dev is already the newest version.
    pkg-config is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

    root@buildroot-trusty:/# go get gopkg.in/lxc/go-lxc.v2
    # gopkg.in/lxc/go-lxc.v2
    tmp/src/gopkg.in/lxc/go-lxc.v2/lxc-binding.go:234: undefined: go_lxc_config_item_is_supported

Seems to be related to accepted pull request #77

**Comment by brauner** [comment]
@towe75, yeah we have a PR open that fixes this issue which will be merged later today.

**Comment by brauner** [comment]
This can be closed. We merged the corresponding PR.
