### ISSUE TITLE
Missing AppendConfigItem

### ISSUE THREAD

**Issue by dcramer** [lxc/go-lxc#8]
Per the Python API, there should be an "append_config_item". Without it I can't see a reliable way to set things like lxc.cgroup.devices.allow which accept multiple values.

**Comment by caglar10ur** [comment]
Makes sense to me. Let me see what I can do.

P.S: Please don't hesitate to report any other problems/inconsistencies/difficulties that you are having with go-lxc. I would like to hear them even if I cannot address them right away.

**Comment by caglar10ur** [comment]
By the way forgot to mention, you can achieve the same by just calling SetConfigItem multiple times. 

``` golang
package main

import (
    "flag"
    "log"

    "github.com/lxc/go-lxc"
)

var (
    lxcpath string
    name    string
)

func init() {
    flag.StringVar(&lxcpath, "lxcpath", lxc.DefaultConfigPath(), "Use specified container path")
    flag.StringVar(&name, "name", "rubik", "Name of the container")
    flag.Parse()
}

func main() {
    c, err := lxc.NewContainer(name, lxcpath)
    if err != nil {
        log.Fatalf("ERROR: %s\n", err.Error())
    }
    defer lxc.PutContainer(c)

    log.Printf("%s", c.ConfigItem("lxc.cgroup.devices.allow"))
    if err := c.SetConfigItem("lxc.cgroup.devices.allow", "b 7:* rwm"); err != nil {
        log.Fatalf("ERROR: %s\n", err.Error())
    }
    log.Printf("%s", c.ConfigItem("lxc.cgroup.devices.allow"))
}
```

```
[caglar@qop:~/go/src/github.com/lxc/go-lxc/examples] sudo ./8
2014/09/28 16:01:10 [c *:* m b *:* m c 1:3 rwm c 1:5 rwm c 5:0 rwm c 5:1 rwm c 1:8 rwm c 1:9 rwm c 5:2 rwm c 136:* rwm c 254:0 rm c 10:229 rwm c 10:200 rwm c 1:7 rwm c 10:228 rwm c 10:232 rwm]
2014/09/28 16:01:10 [c *:* m b *:* m c 1:3 rwm c 1:5 rwm c 5:0 rwm c 5:1 rwm c 1:8 rwm c 1:9 rwm c 5:2 rwm c 136:* rwm c 254:0 rm c 10:229 rwm c 10:200 rwm c 1:7 rwm c 10:228 rwm c 10:232 rwm b 7:* rwm]
[caglar@qop:~/go/src/github.com/lxc/go-lxc/examples]
```

**Comment by dcramer** [comment]
@caglar10ur ah didn't realize that. Will do that for now, thanks!

**Comment by eunosm3** [comment]
How easy is easy?  I might be able to knock out an issue that came up in 2014. (!)

**Comment by stgraber** [comment]
I think we can close this one actually.

In the Python API, set would clear and then set, so we had the separate append function. 

But the Go API instead matches the C one where you just call set multiple times to append.

**Comment by eunosm3** [comment]
Easiest contribution I've ever made.
