### ISSUE TITLE
Wait() function isn't blocking

### ISSUE THREAD

**Issue by skamoen** [lxc/go-lxc#98]
When running the following code, you expect the Wait call to block until the state has been reached, or the timeout has expired.

```
	log.Infof("Waiting for container %s to settle, current state=%s", c.name, c.c.State())

	if !c.c.Wait(lxc.RUNNING, 30*time.Second) {
		return fmt.Errorf("lxccontainer still not running %s", c.name)
	}
```

 However, when running this, I get the following output:
```
13:24:12.422 director/lxc ▶ INFO b38c Waiting for container example to settle, current state=STOPPED
13:24:12.422 director/lxc ▶ ERRO b38d Error creating container: lxccontainer still not running example
```
Running lxc-wait manually works fine, so I think it's a problem somewhere in the binding. Running with lxc-2.1

**Comment by brauner** [comment]
Right, this should be closed by https://github.com/lxc/lxc/pull/2089 .
